#ifndef CONFIG_HPP
#define CONFIG_HPP


#define PLAYER_MAX_STAMINA 100
#define STAMINA_COST_DASH 20
#define STAMINA_COST_DOWNSTAB 20
#define STAMINA_REGEN_RATE 1
#define STAMINA_REGEN_INTERVAL 20

#define UI_BAR_X 20
#define UI_BAR_Y 490
#define UI_BAR_WIDTH 250
#define UI_BAR_HEIGHT 100
#define UI_BAR_SPACING 50

#define INVENTORY_W 150
#define INVENTORY_H 300
#define INVENTORY_X -10
#define INVENTORY_Y 215
#define PICKUP_SIZE 48
#define PICKUP_DROP_CHANCE 75
#define MAX_PICKUPS 10

#define POTION_DURATION 500
#define POTION_DAMAGE_MULTIPLIER 2

#define POWER_DAMAGE_PERCENT 20
#define GLOW_FRAMES 5
#define GLOW_SIZE 48
#define GLOW_SPEED 10

#define HEART_DURATION 500
#define HEART_REGEN_INTERVAL 150
#define HEART_REGEN_AMOUNT 20

#define GAIN_DURATION 600
#define GAIN_REGEN_INTERVAL 180
#define GAIN_REGEN_AMOUNT 20

#define ATTACK_FRAMES 10
#define PLAYER_MAX_HEALTH 100
#define ATTACK_RANGE 60
#define ATTACK_RANGE_LEFT 2
#define SLASHWAVE_RANGE 20
#define ATTACK_HORIZONTAL_OFFSET 40
#define POST_ATTACK_INVINCIBILITY_DURATION 0
#define DOWNSTAB_INVINCIBILITY_DURATION 180

#define TITLE_SCREEN_STATE 0
#define PLAYING_STATE 1
#define TUNNEL_STATE 2
#define LEVEL2_STATE 3
#define CREDITS_STATE 4
#define CONTROLS_STATE 5
#define CAVE_STATE 6
#define LOADING_STATE 7
#define LEVEL3_STATE 8
#define BOSS_STATE 9
#define GAME_OVER_STATE 10
#define PAUSED_STATE 11
#define BOSS_ENTRY_STATE 12
#define GAME_ENDING_STATE 13
#define CONGRATS_STATE 14

#define GAME_OVER_FRAMES 65
#define BOSS_ENTRY_FRAMES 278
#define GAME_ENDING_FRAMES 277

#define SCREEN_W 1000
#define SCREEN_H 600

#define GROUND_Y 25
#define SPEED 6
#define JUMP_V 18
#define GRAVITY 1
#define LEVEL2_GROUND_Y 2
#define LEVEL2_PIT_X_START 4012
#define LEVEL2_PIT_X_END 4210
#define LEVEL2_RAISED_GROUND_X 4210
#define LEVEL2_RAISED_GROUND_Y 150

#define CAVE_ENTRY_X 710
#define CAVE_ENTRY_Y 600
#define CAVE_LAND_X 710
#define CAVE_LAND_Y 10
#define CAVE_GROUND_Y 10

#define LEVEL3_GROUND_Y 55
#define BOSS_GROUND_Y 63
#define LEVEL2_END_X 4870
#define LEVEL3_END_X 4870

#define GREET_IDLE_FRAMES 1
#define GREET_ANIM_FRAMES 8
#define GREET_ANIM_SPEED 8
#define GREET_SIZE_W 75
#define GREET_SIZE_H 150
#define GREET_X 4850
#define GREET_Y LEVEL2_RAISED_GROUND_Y + 50
#define GREET_TRIGGER_X_START 4750
#define GREET_TRIGGER_X_END LEVEL2_END_X

#define LEVEL3_TILE_COUNT 5
#define LEVEL3_TILE_W TILE_WIDTH
#define LEVEL3_TILE_H TILE_HEIGHT
#define LEVEL3_TILE_WIDE_W (int)(TILE_WIDTH * 1.5)
#define LEVEL3_TILE_BASE_HEIGHT (LEVEL3_GROUND_Y + 125)
#define LEVEL3_TILE_1_X 700
#define LEVEL3_TILE_1_Y 0
#define LEVEL3_TILE_2_X 1500
#define LEVEL3_TILE_2_Y 50
#define LEVEL3_TILE_3_X 2500
#define LEVEL3_TILE_3_Y 30
#define LEVEL3_TILE_4_X 3400
#define LEVEL3_TILE_4_Y 60
#define LEVEL3_TILE_5_X 4200
#define LEVEL3_TILE_5_Y 40

#define TRADER_KEY_DISPLAY_SIZE 85
#define TRADER_KEY_PROMPT_Y 110
#define TRADER_KEY_PROMPT_X_OFFSET (TRADER_SIZE / 2 - TRADER_KEY_DISPLAY_SIZE / 2)

#define DASH_SPEED 6
#define EVADE_SPEED 10
#define DOWNSTAB_VELOCITY -25

#define BUG_MAX_HEALTH 100
#define SENTRY_MAX_HEALTH 140

#define DAMAGE_PLAYER_TAKES 20
#define DAMAGE_DEALT_NORMAL 20
#define DAMAGE_DEALT_HEAVY 35



#define IDLE_FRAMES 8
#define WALK_FRAMES 7
#define TURN_FRAMES 1
#define JUMP_LEFT_FRAMES 8
#define JUMP_RIGHT_FRAMES 8
#define FALL_LEFT_FRAMES 7
#define FALL_RIGHT_FRAMES 7
#define LAND_FRAMES 7

#define DASH_LEFT_FRAMES 5
#define DASH_RIGHT_FRAMES 5
#define DOWNSTAB_ANTICIPATE_FRAMES 6
#define DOWNSTAB_SLAM_FRAMES 5
#define DOWNSTAB_LAND_FRAMES 7

#define OVERHEAD_ATTACK_RECOVER_FRAMES 2
#define OVERHEAD_ATTACK_SLASHING_FRAMES 7
#define OVERHEAD_ATTACK_SLASHWAVE_FRAMES 3

#define EVADE_LEFT_PRE_FRAMES 2
#define EVADE_LEFT_ACTIVE_FRAMES 4
#define EVADE_LEFT_RECOVER_FRAMES 1
#define EVADE_RIGHT_PRE_FRAMES 2
#define EVADE_RIGHT_ACTIVE_FRAMES 4
#define EVADE_RIGHT_RECOVER_FRAMES 1

#define DEATH_FRAMES 16
#define WAKE_FRAMES_PART1 3
#define WAKE_FRAMES_PART2 3
#define WAKE_FRAMES_PART3 3
#define ROAR_FRAMES 4
#define ROAR_ACTIVE_FRAMES 2
#define ROAR_END_FRAMES 1
#define INTRO_ANIMATION_SPEED 15
#define DEATH_ANIMATION_DURATION 100

#define SPRITE_SIZE 512
#define SCALE 0.25

#define BG_SCROLL_SPEED 2
#define BG_WIDTH 1000
#define BG_HEIGHT 600
#define BG_SEGMENTS 5
#define TOTAL_BG_WIDTH (BG_WIDTH * BG_SEGMENTS)

#define MAX_TILES 100
#define TILE_WIDTH 128
#define TILE_HEIGHT 64
#define TILE_SCALE_FACTOR 1.5

#define TILE1_SURFACE_Y_OFFSET 65
#define TILE2_SURFACE_Y_OFFSET 49
#define JUMP_DOWN_VELOCITY -15
#define TILES_PER_ROW 2
#define TILE_ROWS_ABOVE 2
#define TILE_ROWS_BELOW 2
#define TILE_SPACING_X 150
#define TILE_SPACING_Y 100
#define TUNNEL_HOLE_X 4930
#define TUNNEL_HOLE_Y GROUND_Y

#define CAMERA_FOLLOW_SPEED 0.1
#define CAMERA_EDGE_MARGIN 200

#define MAX_CREATURES 3
#define CREATURE_NORMAL_FRAMES 5
#define CREATURE_FLYL_FRAMES 6
#define CREATURE_FLYR_FRAMES 5
#define CREATURE_TURN_FRAMES 2
#define CREATURE_ATTACK_FRAMES 3
#define CREATURE_BURST_FRAMES 5
#define CREATURE_DAMAGE_FRAMES 3
#define CREATURE_SPEED 2
#define CREATURE_ATTACK_SPEED 4
#define CREATURE_ATTACK_RANGE 150

#define CREATURE_ATTACK_COOLDOWN 70
#define CREATURE_DETECTION_RANGE 300
#define CREATURE_SPAWN_TRIGGER 400
#define CREATURE_SIZE 64
#define CREATURE_PATROL_DISTANCE 120
#define SPAWN_POINT_1_X 800
#define SPAWN_POINT_2_X 2500
#define SPAWN_POINT_3_X 4500
#define SPAWN_POINT_Y GROUND_Y

#define SENTRY_IDLE_FRAMES 5
#define SENTRY_WALKL_FRAMES 8
#define SENTRY_WALKR_FRAMES 8
#define SENTRY_RUNL_FRAMES 8
#define SENTRY_RUNR_FRAMES 8
#define SENTRY_ATTACKL_FRAMES 12
#define SENTRY_ATTACKR_FRAMES 12
#define SENTRY_SLASHL_FRAMES 4
#define SENTRY_SLASHR_FRAMES 4
#define SENTRY_TURNL_FRAMES 2
#define SENTRY_TURNR_FRAMES 2
#define SENTRY_WAKE_FRAMES 7
#define SENTRY_DEATH_FRAMES 3
#define SENTRY_DEATHAIR_FRAMES 2
#define SENTRY_DAMAGE_FRAMES 3
#define SENTRY_SIZE 128
#define SENTRY_SPEED 2
#define SENTRY_ATTACK_SPEED 4
#define SENTRY_ATTACK_RANGE 150

#define SENTRY_ATTACK_COOLDOWN 70
#define SENTRY_DETECTION_RANGE 250
#define SENTRY_PATROL_DISTANCE 120
#define SENTRY_MAX_CHASE_DIST 250
#define SENTRY_RUN_SPEED 5
#define SENTRY_JUMP_V 18
#define SENTRY_IDLE_CHANCE 20
#define SENTRY_ATTACK_JUMP_CHANCE 40
#define MAX_SENTRIES 3

#define SENTRY_SPAWN_1_X 1300
#define SENTRY_SPAWN_2_X 3100
#define SENTRY_SPAWN_3_X 3800

// Level 3 enemy spawn points
#define SPAWN_POINT_L3_1_X 1200
#define SPAWN_POINT_L3_2_X 2600
#define SPAWN_POINT_L3_3_X 4000

#define SENTRY_SPAWN_L3_1_X 1900
#define SENTRY_SPAWN_L3_2_X 3300
#define SENTRY_SPAWN_L3_3_X 4600

#define SPARKLE_FRAMES 8
#define MAX_SPARKLES 5

#define SPARKLE_1_X 800
#define SPARKLE_1_Y 350
#define SPARKLE_2_X 850
#define SPARKLE_2_Y 325
#define SPARKLE_3_X 3000
#define SPARKLE_3_Y 330
#define SPARKLE_4_X 3800
#define SPARKLE_4_Y 480
#define SPARKLE_5_X 4800
#define SPARKLE_5_Y 500

#define TITLE_SKY_FRAMES 27
#define TITLE_FIRE_FRAMES 27
#define TITLE_TRANSITION_FRAMES 2
#define TITLE_ANIMATION_SPEED 8


#define CREST_INVENTORY_X 900
#define CREST_INVENTORY_Y 370
#define CREST_INVENTORY_W 80
#define CREST_INVENTORY_H 150
#define CREST_KEY_OFFSET_X 20
#define CREST_KEY_OFFSET_Y 57
#define CREST_KEY_SIZE 35






#define TRADER_NPC_X 2900
#define TRADER_NPC_Y LEVEL3_GROUND_Y+12
#define TRADER_IDLE_FRAMES 8
#define TRADER_WALK_L_FRAMES 9
#define TRADER_WALK_R_FRAMES 9
#define TRADER_TURN_FRAMES 2
#define TRADER_TRADE_FRAMES 4
#define TRADER_DETECTION_RADIUS 300
#define TRADER_STOP_RADIUS 70
#define TRADER_WALK_SPEED 3
#define TRADER_ANIM_SPEED 6
#define TRADER_SIZE 128

#define GRIM_MAX_HEALTH 250
#define GRIM_IDLE_FRAMES 10
#define GRIM_TURN_L_FRAMES 3
#define GRIM_TURN_R_FRAMES 3
#define GRIM_DASH_ANTIC_L_FRAMES 8
#define GRIM_DASH_ANTIC_R_FRAMES 8
#define GRIM_DASH_L_FRAMES 5
#define GRIM_DASH_R_FRAMES 5
#define GRIM_DEATH_FRAMES 3
#define GRIM_THROW_ANTIC_L_FRAMES 5
#define GRIM_THROW_ANTIC_R_FRAMES 5
#define GRIM_THROW_L_FRAMES 3
#define GRIM_THROW_R_FRAMES 3
#define GRIM_FIREBALL_FRAMES 8
#define GRIM_FIREBALL_EXPLODE_FRAMES 4
#define GRIM_TELEPORT_IN_PILLAR_FRAMES 6
#define GRIM_TELEPORT_IN_FRAMES 9
#define GRIM_TELEPORT_OUT_FRAMES 6
#define GRIM_TELEPORT_OUT_PILLAR_FRAMES 6
#define GRIM_SIZE 220
#define GRIM_SPEED 4
#define GRIM_DASH_SPEED 15
#define GRIM_DETECTION_RANGE 390
#define GRIM_DASH_RANGE 200
#define GRIM_ATTACK_RANGE 300
#define GRIM_FIREBALL_SPEED 12
#define GRIM_FIREBALL_SIZE 50
#define GRIM_FIREBALL_DISPLAY_SIZE 50
#define GRIM_FIREBALL_EXPLODE_DISPLAY_SIZE 100
#define GRIM_FIREBALL_HIT_W 120
#define GRIM_FIREBALL_HIT_H 120
#define GRIM_ANIM_SPEED 4
#define GRIM_TELEPORT_CHANCE 6
#define GRIM_THROW_CHANCE 6
#define GRIM_TELEPORT_RADIUS 250
#define GRIM_INVINCIBILITY_FRAMES 90
#define GRIM_DAMAGE_FRAMES 3
#define MAX_GRIMS 2
#define GRIM_SPAWN_1_X 1000
#define GRIM_SPAWN_2_X 3910
#define GRIM_SPAWN_Y_OFFSET 82
#define GRIM_FIREBALL_DAMAGE 15
#define GRIM_CONTACT_DAMAGE 10
#define MAX_GRIM_FIREBALLS 6

#define GRIM_FB_SPAWN_OFFSET_X_RIGHT 100  
#define GRIM_FB_SPAWN_OFFSET_X_LEFT  100 
#define GRIM_FB_SPAWN_OFFSET_Y       130  
#define GRIM_FB_TARGET_PLAYER_OFFSET_X 300 
#define GRIM_FB_TARGET_GROUND_OFFSET   30  

#define TRADE_ITEM_COST_SWIFTNESS 5
#define TRADE_ITEM_COST_SOUL 5
#define TRADE_ITEM_COST_KEY 0

#define SWIFTNESS_SPEED_MULTIPLIER 1.4f
#define SOUL_REGEN_ON_KILL 20  

#define TRADE_LIST_X 180
#define TRADE_LIST_Y 50
#define TRADE_LIST_W 800
#define TRADE_LIST_H 480

#define TRADE_FRAGMENT_X (TRADE_LIST_X)
#define TRADE_FRAGMENT_Y (TRADE_LIST_Y)
#define TRADE_FRAGMENT_W 800
#define TRADE_FRAGMENT_H 480
#define TRADE_FRAGMENT_TEXT_OFFSET_X 88   
#define TRADE_FRAGMENT_TEXT_OFFSET_Y 34   

#define TRADE_TOTAL_FRAGMENT_X 843
#define TRADE_TOTAL_FRAGMENT_Y 456

#define TRADE_ITEM_W 175
#define TRADE_ITEM_H 70

#define TRADE_SWIFTNESS_X1 (TRADE_LIST_X + 150)
#define TRADE_SWIFTNESS_Y1 (TRADE_LIST_Y + 311)
#define TRADE_SWIFTNESS_X2 (TRADE_SWIFTNESS_X1 + TRADE_ITEM_W)
#define TRADE_SWIFTNESS_Y2 (TRADE_SWIFTNESS_Y1 + TRADE_ITEM_H)

#define TRADE_SOUL_X1 (TRADE_LIST_X + 150)
#define TRADE_SOUL_Y1 (TRADE_LIST_Y + 209)
#define TRADE_SOUL_X2 (TRADE_SOUL_X1 + TRADE_ITEM_W)
#define TRADE_SOUL_Y2 (TRADE_SOUL_Y1 + TRADE_ITEM_H)

#define TRADE_KEY_X1 (TRADE_LIST_X + 150)
#define TRADE_KEY_Y1 (TRADE_LIST_Y + 105)
#define TRADE_KEY_X2 (TRADE_KEY_X1 + TRADE_ITEM_W)
#define TRADE_KEY_Y2 (TRADE_KEY_Y1 + TRADE_ITEM_H)

#define TRADE_DESC_X 180
#define TRADE_DESC_Y 50
#define TRADE_DESC_W 800
#define TRADE_DESC_H 480
#define TRADE_DESC_Y_OFFSET 0  

#define TRADE_COST_ICON_W 0
#define TRADE_COST_ICON_H 0
#define TRADE_COST_ICON_Y_OFFSET (-35)  
#define TRADE_COST_TEXT_X_OFFSET 34     
#define TRADE_COST_TEXT_Y_OFFSET 8     

#define TRADE_HOVER_OFFSET 12

#define EQUIPPED_ICON_SIZE 40
#define EQUIPPED_ICON_X 910
#define EQUIPPED_ICON_Y 550
#define EQUIPPED_ICON_SPACING 50

#define DOOR_LOCKED_FRAMES 3
#define DOOR_OPEN_FRAMES 6
#define DOOR_X 4850
#define DOOR_Y LEVEL3_GROUND_Y+50
#define DOOR_W 120
#define DOOR_H 180
#define DOOR_ANIM_SPEED 6

// "Twin Switch Gate" puzzle — sits between the trader (x=2900) and the
// boss door (x=4850).
#define MAX_PUZZLE_SWITCHES 2

#define SWITCH_W 60
#define SWITCH_H 20

#define PUSH_BLOCK_W 80
#define PUSH_BLOCK_H 80
#define PUSH_BLOCK_SPEED 3

#define PUZZLE_GATE_LOCKED_FRAMES 4
#define PUZZLE_GATE_OPEN_FRAMES 8
#define PUZZLE_GATE_W 120
#define PUZZLE_GATE_H 180
#define PUZZLE_GATE_ANIM_SPEED 6

#define SWITCH_1_X 3200
#define SWITCH_1_Y LEVEL3_GROUND_Y
#define SWITCH_2_X 3450
#define SWITCH_2_Y LEVEL3_GROUND_Y

#define PUSH_BLOCK_START_X 3300

#define PUZZLE_GATE_X 3600
#define PUZZLE_GATE_Y (LEVEL3_GROUND_Y + 50)

// Keeps the block from being shoved out of the puzzle room
#define PUZZLE_ROOM_MIN_X 3150
#define PUZZLE_ROOM_MAX_X 3550

#define BOSS_MAX_HEALTH 400
#define BOSS_NORMAL_HIT_DAMAGE 5    
#define BOSS_SLASHWAVE_HIT_DAMAGE 7  
#define BOSS_INVINCIBILITY_FRAMES 30 

#define BOSS_SLASH_PLAYER_DAMAGE 20
#define BOSS_DASH_PLAYER_DAMAGE 20
#define BOSS_SPIKE_PLAYER_DAMAGE 20

#define BOSS_PHASE2_THRESHOLD 50 
#define BOSS_TRAP_THRESHOLD 25   

#define BOSS_SPAWN_X 700 
#define BOSS_RAND_TELEPORT_MIN 100 
#define BOSS_RAND_TELEPORT_MAX 700 
#define BOSS_SIZE_W 128
#define BOSS_SIZE_H 128
#define BOSS_WALK_SPEED 4
#define BOSS_DASH_SPEED 10
#define BOSS_DETECTION_RANGE 500 
#define BOSS_SLASH_RANGE 120     

#define BOSS_IDLE_DURATION 50     
#define BOSS_POST_SPIKE_IDLE 50    
#define BOSS_DEATH_RISE_HEIGHT 120 
#define BOSS_DEATH_RISE_SPEED 2    
#define BOSS_ANIM_SPEED 6         

#define BOSS_IDLE_FRAMES 4
#define BOSS_WALK_FRAMES 3
#define BOSS_SLASH_FRAMES 8
#define BOSS_DASH_FRAMES 6
#define BOSS_CAST_FRAMES 6
#define BOSS_TELEPORT_FRAMES 6
#define BOSS_SPIKE_FRAMES 10
#define BOSS_TRAPIN_FRAMES 3
#define BOSS_TRAPOUT_FRAMES 3
#define BOSS_DEATH_FRAMES 9

#define FIREBAT_MAX_HEALTH 2 
#define FIREBAT_SPEED 4
#define FIREBAT_DAMAGE 10 
#define FIREBAT_FRAMES 5
#define FIREBAT_SIZE 64
#define FIREBAT_ANIM_SPEED 6
#define FIREBAT_INVINCIBILITY 20

#define BAT_MAX_HEALTH 2 
#define BAT_SPEED 3
#define BAT_DAMAGE 10 
#define BAT_FRAMES 3
#define BAT_DEATH_FRAMES 2
#define BAT_SIZE 48
#define BAT_ANIM_SPEED 6
#define BAT_INVINCIBILITY 20

#define MAX_BOSS_MINIONS 4
#define MAX_BOSS_HAZARDS 4


#define QUIT_BG_X 0
#define QUIT_BG_Y 0
#define QUIT_BG_W SCREEN_W
#define QUIT_BG_H SCREEN_H

#define QUIT_BTN_W 90
#define QUIT_BTN_H 50
#define QUIT_YES_X 460
#define QUIT_YES_Y 270
#define QUIT_NO_X  464
#define QUIT_NO_Y  220

#define QUIT_ARROW_W 1000
#define QUIT_ARROW_H 600
#define QUIT_ARROW1_X 0
#define QUIT_ARROW1_Y 0
#define QUIT_ARROW2_X 0
#define QUIT_ARROW2_Y 0

#define QUIT_HOVER_OFFSET 4




#define PLAYER_WALK_FRAMES 7
#define PLAYER_IDLE_FRAMES 5
#define PLAYER_SLASH_FRAMES 7
#define PLAYER_ANIM_FRAME_DELAY 6


#define PLAYER_ARROW_FRAMES 10
#define ARROW_FLY_FRAMES 5
#define MAX_ARROWS 5
#define ARROW_VERTICAL_RANGE 600


#define PLAYER_WIDTH 80
#define PLAYER_HEIGHT 100

#define LEVEL1_END_X 4800


#define LEVEL2_FINISH_X LEVEL2_END_X


#define LEVEL_COMPLETE_STATE 20


#define AGGRO_LOSE_BUFFER 150

#endif


#define LEVEL1_CLEARED_STATE 15
#define LEVEL1_CLEARED_FRAMES 100
#define CAVE_BUG_MAX 5
#define CAVE_BUG_WIDTH 80
#define CAVE_BUG_HEIGHT 80
#define CAVE_BUG_SPAWN_X 900
#define CAVE_RANDOM_SPAWN_TRIGGER_X 800
#define CAVE_RANDOM_SPAWN_MIN_DISTANCE 140
#define CAVE_RANDOM_SPAWN_POINT_COUNT 5
#define CAVE_RANDOM_SPAWN_X1 720
#define CAVE_RANDOM_SPAWN_X2 780
#define CAVE_RANDOM_SPAWN_X3 840
#define CAVE_RANDOM_SPAWN_X4 900
#define CAVE_RANDOM_SPAWN_X5 920
#define CAVE_BUG_SPAWN_Y GROUND_Y
#define CAVE_BUG_MAX_HP 60
#define CAVE_BUG_DAMAGE_TO_PLAYER 10
#define CAVE_BUG_MOVE_SPEED 3
#define CAVE_BUG_ATTACK_RANGE 60
#define CAVE_BUG_ANIM_SPEED 6
#define CAVE_BUG_SPAWN_DELAY 40
#define CAVE_BUG_EMERGE_FRAMES 10
#define CAVE_BUG_RUN_CHARGE_FRAMES 17
#define CAVE_BUG_SMASH_FRAMES 9
#define CAVE_BUG_DEATH_FRAMES 10
#define CAVE_GOBLIN_MAX 3
#define CAVE_GOBLIN_WIDTH 70
#define CAVE_GOBLIN_HEIGHT 100
#define CAVE_GOBLIN_SPAWN_X 900
#define CAVE_GOBLIN_SPAWN_Y GROUND_Y 
#define CAVE_GOBLIN_MAX_HP 80
#define CAVE_GOBLIN_DAMAGE_TO_PLAYER 15
#define CAVE_GOBLIN_MOVE_SPEED 2
#define CAVE_GOBLIN_ATTACK_RANGE 70
#define CAVE_GOBLIN_ANIM_SPEED 6
#define CAVE_GOBLIN_SPAWN_DELAY 40
#define CAVE_GOBLIN_WALK_FRAMES 5
#define CAVE_GOBLIN_SPIN_ATTACK_FRAMES 5
#define CAVE_GOBLIN_TAKEDAMAGE_FRAMES 5
#define CAVE_GOBLIN_DEATH_FRAMES 6
#define CAVE_GRIMMASTER_WIDTH 140
#define CAVE_GRIMMASTER_HEIGHT 140
#define CAVE_GRIMMASTER_MAX_HP 500
#define CAVE_GRIMMASTER_SPAWN_X 700
#define CAVE_GRIMMASTER_SPAWN_Y 300
#define CAVE_GRIMMASTER_DAMAGE_TO_PLAYER 20
#define CAVE_GRIMMASTER_ATTACK_RANGE 250
#define CAVE_GRIMMASTER_ANIM_SPEED 6
#define CAVE_GRIMMASTER_ATTACK_RAP_FRAMES 5
#define CAVE_GRIMMASTER_TENTACLE_HARPOON_FRAMES 5
#define CAVE_GRIMMASTER_FLIGHT_FRAMES 5
#define CAVE_GRIMMASTER_FLINCH_FRAMES 6
#define CAVE_GRIMMASTER_DEATH_FRAMES 7
#define CAVE_BOSS_UNLOCK_X (CAVE_LAND_X + 200)
